
import { PhonicSound } from './types';

export const PHONETIC_SOUNDS: PhonicSound[] = [
  // --- VOWELS ---
  { id: 'v1', symbol: 'iː', type: 'VOWEL', description: 'Long E as in "Sheep"' },
  { id: 'v2', symbol: 'ɪ', type: 'VOWEL', description: 'Short I as in "Ship"' },
  { id: 'v3', symbol: 'e', type: 'VOWEL', description: 'Short E as in "Bed"' },
  { id: 'v4', symbol: 'æ', type: 'VOWEL', description: 'Short A as in "Cat"' },
  { id: 'v5', symbol: 'ʌ', type: 'VOWEL', description: 'Short U as in "Cup"' },
  { id: 'v6', symbol: 'ɑː', type: 'VOWEL', description: 'Long A as in "Father"' },
  { id: 'v7', symbol: 'ɒ', type: 'VOWEL', description: 'Short O as in "Hot"' },
  { id: 'v8', symbol: 'ɔː', type: 'VOWEL', description: 'Long O as in "Door"' },
  { id: 'v9', symbol: 'ʊ', type: 'VOWEL', description: 'Short OO as in "Book"' },
  { id: 'v10', symbol: 'uː', type: 'VOWEL', description: 'Long OO as in "Too"' },
  { id: 'v11', symbol: 'ɜː', type: 'VOWEL', description: 'Bird vowel as in "Bird"' },
  { id: 'v12', symbol: 'ə', type: 'VOWEL', description: 'Schwa as in "About"' },
  { id: 'd1', symbol: 'eɪ', type: 'VOWEL', description: 'A as in "Say"' },
  { id: 'd2', symbol: 'aɪ', type: 'VOWEL', description: 'I as in "My"' },
  { id: 'd3', symbol: 'ɔɪ', type: 'VOWEL', description: 'OY as in "Boy"' },
  { id: 'd4', symbol: 'əʊ', type: 'VOWEL', description: 'O as in "Go"' },
  { id: 'd5', symbol: 'aʊ', type: 'VOWEL', description: 'OW as in "Now"' },
  { id: 'd6', symbol: 'ɪə', type: 'VOWEL', description: 'EAR as in "Near"' },
  { id: 'd7', symbol: 'eə', type: 'VOWEL', description: 'AIR as in "Hair"' },
  { id: 'd8', symbol: 'ʊə', type: 'VOWEL', description: 'URE as in "Pure"' },

  // --- CONSONANTS ---
  { id: 'c1', symbol: 'p', type: 'CONSONANT', description: 'P as in "Pen"' },
  { id: 'c2', symbol: 'b', type: 'CONSONANT', description: 'B as in "Bad"' },
  { id: 'c3', symbol: 't', type: 'CONSONANT', description: 'T as in "Tea"' },
  { id: 'c4', symbol: 'd', type: 'CONSONANT', description: 'D as in "Did"' },
  { id: 'c5', symbol: 'k', type: 'CONSONANT', description: 'K as in "Cat"' },
  { id: 'c6', symbol: 'ɡ', type: 'CONSONANT', description: 'G as in "Get"' },
  { id: 'c7', symbol: 'f', type: 'CONSONANT', description: 'F as in "Fall"' },
  { id: 'c8', symbol: 'v', type: 'CONSONANT', description: 'V as in "Voice"' },
  { id: 'c9', symbol: 'θ', type: 'CONSONANT', description: 'Voiceless TH as in "Think"' },
  { id: 'c10', symbol: 'ð', type: 'CONSONANT', description: 'Voiced TH as in "That"' },
  { id: 'c11', symbol: 's', type: 'CONSONANT', description: 'S as in "So"' },
  { id: 'c12', symbol: 'z', type: 'CONSONANT', description: 'Z as in "Zoo"' },
  { id: 'c13', symbol: 'ʃ', type: 'CONSONANT', description: 'SH as in "Ship"' },
  { id: 'c14', symbol: 'ʒ', type: 'CONSONANT', description: 'ZH as in "Measure"' },
  { id: 'c15', symbol: 'h', type: 'CONSONANT', description: 'H as in "How"' },
  { id: 'c16', symbol: 'tʃ', type: 'CONSONANT', description: 'CH as in "Church"' },
  { id: 'c17', symbol: 'dʒ', type: 'CONSONANT', description: 'J as in "Joy"' },
  { id: 'c18', symbol: 'm', type: 'CONSONANT', description: 'M as in "Man"' },
  { id: 'c19', symbol: 'n', type: 'CONSONANT', description: 'N as in "No"' },
  { id: 'c20', symbol: 'ŋ', type: 'CONSONANT', description: 'NG as in "Sing"' },
  { id: 'c21', symbol: 'l', type: 'CONSONANT', description: 'L as in "Light"' },
  { id: 'c22', symbol: 'r', type: 'CONSONANT', description: 'R as in "Red"' },
  { id: 'c23', symbol: 'j', type: 'CONSONANT', description: 'Y as in "Yes"' },
  { id: 'c24', symbol: 'w', type: 'CONSONANT', description: 'W as in "Wet"' },

  // --- INITIAL CLUSTERS ---
  { id: 'icl-sp', symbol: 'sp', type: 'INITIAL_CLUSTER', description: 'sp- as in "speak"' },
  { id: 'icl-st', symbol: 'st', type: 'INITIAL_CLUSTER', description: 'st- as in "stick"' },
  { id: 'icl-sk', symbol: 'sk', type: 'INITIAL_CLUSTER', description: 'sk- as in "sky"' },
  { id: 'icl-sl', symbol: 'sl', type: 'INITIAL_CLUSTER', description: 'sl- as in "slide"' },
  { id: 'icl-sm', symbol: 'sm', type: 'INITIAL_CLUSTER', description: 'sm- as in "smile"' },
  { id: 'icl-sn', symbol: 'sn', type: 'INITIAL_CLUSTER', description: 'sn- as in "snake"' },
  { id: 'icl-sw', symbol: 'sw', type: 'INITIAL_CLUSTER', description: 'sw- as in "swim"' },
  { id: 'icl-bl', symbol: 'bl', type: 'INITIAL_CLUSTER', description: 'bl- as in "blue"' },
  { id: 'icl-cl', symbol: 'cl', type: 'INITIAL_CLUSTER', description: 'cl- as in "clap"' },
  { id: 'icl-fl', symbol: 'fl', type: 'INITIAL_CLUSTER', description: 'fl- as in "fly"' },
  { id: 'icl-gl', symbol: 'gl', type: 'INITIAL_CLUSTER', description: 'gl- as in "glue"' },
  { id: 'icl-pl', symbol: 'pl', type: 'INITIAL_CLUSTER', description: 'pl- as in "play"' },
  { id: 'icl-br', symbol: 'br', type: 'INITIAL_CLUSTER', description: 'br- as in "bring"' },
  { id: 'icl-cr', symbol: 'cr', type: 'INITIAL_CLUSTER', description: 'cr- as in "cream"' },
  { id: 'icl-dr', symbol: 'dr', type: 'INITIAL_CLUSTER', description: 'dr- as in "drink"' },
  { id: 'icl-fr', symbol: 'fr', type: 'INITIAL_CLUSTER', description: 'fr- as in "friend"' },
  { id: 'icl-gr', symbol: 'gr', type: 'INITIAL_CLUSTER', description: 'gr- as in "grass"' },
  { id: 'icl-pr', symbol: 'pr', type: 'INITIAL_CLUSTER', description: 'pr- as in "pray"' },
  { id: 'icl-tr', symbol: 'tr', type: 'INITIAL_CLUSTER', description: 'tr- as in "train"' },
  { id: 'icl-tw', symbol: 'tw', type: 'INITIAL_CLUSTER', description: 'tw- as in "twin"' },
  { id: 'icl-dw', symbol: 'dw', type: 'INITIAL_CLUSTER', description: 'dw- as in "dwarf"' },
  { id: 'icl-spl', symbol: 'spl', type: 'INITIAL_CLUSTER', description: 'spl- as in "splash"' },
  { id: 'icl-spr', symbol: 'spr', type: 'INITIAL_CLUSTER', description: 'spr- as in "spring"' },
  { id: 'icl-str', symbol: 'str', type: 'INITIAL_CLUSTER', description: 'str- as in "street"' },
  { id: 'icl-scr', symbol: 'scr', type: 'INITIAL_CLUSTER', description: 'scr- as in "screen"' },

  // --- FINAL CLUSTERS ---
  { id: 'fcl1', symbol: 'st', type: 'FINAL_CLUSTER', description: '-ST cluster as in "Best"' },
  { id: 'fcl2', symbol: 'nd', type: 'FINAL_CLUSTER', description: '-ND cluster as in "Hand"' },
  { id: 'fcl3', symbol: 'nt', type: 'FINAL_CLUSTER', description: '-NT cluster as in "Tent"' },
  { id: 'fcl4', symbol: 'nk', type: 'FINAL_CLUSTER', description: '-NK cluster as in "Pink"' },
  { id: 'fcl5', symbol: 'mp', type: 'FINAL_CLUSTER', description: '-MP cluster as in "Camp"' },
  { id: 'fcl6', symbol: 'lt', type: 'FINAL_CLUSTER', description: '-LT cluster as in "Belt"' },
  { id: 'fcl7', symbol: 'ld', type: 'FINAL_CLUSTER', description: '-LD cluster as in "Gold"' },
  { id: 'fcl8', symbol: 'ts', type: 'FINAL_CLUSTER', description: '-TS cluster as in "Cats"' },
  { id: 'fcl9', symbol: 'dz', type: 'FINAL_CLUSTER', description: '-DZ cluster as in "Birds"' },
  { id: 'fcl10', symbol: 'ks', type: 'FINAL_CLUSTER', description: '-KS cluster as in "Books"' },
  { id: 'fcl11', symbol: 'gz', type: 'FINAL_CLUSTER', description: '-GZ cluster as in "Eggs"' },
  { id: 'fcl12', symbol: 'ft', type: 'FINAL_CLUSTER', description: '-FT cluster as in "Soft"' },
  { id: 'fcl13', symbol: 'sk', type: 'FINAL_CLUSTER', description: '-SK cluster as in "Ask"' },
  { id: 'fcl14', symbol: 'pt', type: 'FINAL_CLUSTER', description: '-PT cluster as in "Kept"' },
  { id: 'fcl15', symbol: 'kt', type: 'FINAL_CLUSTER', description: '-KT cluster as in "Fact"' },

  // --- ENDING SOUND MASTERCLASS ---
  { id: 'ep1', symbol: 'Plurals', type: 'ENDING_PATTERN', patternGroup: 'PLURALS', description: 'Final sounds /s/, /z/, /ɪz/ for plurals & present tense verbs' },
  { id: 'ep2', symbol: 'Past Tense', type: 'ENDING_PATTERN', patternGroup: 'PAST_TENSE', description: 'Final sounds /t/, /d/, /ɪd/ for past tense verbs' },

  // --- CONNECTED SPEECH MASTERCLASS ---
  { id: 'ls1', symbol: 'Linking', type: 'LINKING_PATTERN', patternGroup: 'CONSONANT_VOWEL', description: 'Connected speech: Linking final consonant to initial vowel' },
];

export const APP_STORAGE_KEY = 'speakfun_data_v1';
